disabled_rules:
  - force_try
  - missing_docs
included: # paths to include during linting. `--path` is ignored if present.
  - Wallet
  - Modules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

identifier_name:
  min_length: 2
  max_length: 
    warning: 90
    error: 1000
  excluded:
  - dy
  - id
  - ip
  - i
  - s
  - j
  - x
  - y
  - qa
  - to

force_cast: warning

file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 250
  error: 400

type_name:
  max_length:
    warning: 45
    error: 55
  min_length:
    warning: 3
    error: 0

function_body_length:
  warning: 40
  error: 100

function_parameter_count:
  warning: 5
  error: 8

line_length:
  warning: 105
  error: 150
  ignores_urls: true
  ignores_interpolated_strings: true
  ignores_comments: true
  ignores_function_declarations: true

identifier_name:
  max_length:
    warning: 45
    error: 55
  min_length:
    warning: 3
    error: 0
  # allowed_symbols: []
  validates_start_with_lowercase: false

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

cyclomatic_complexity:
  warning: 5
  error: 10
  ignores_case_statements: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true