name: Xcode - Build and Analyze

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: '16.0'
      # Run tests on iPhone 16 Simulator with iOS 18.0
      - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
        run: |
          xcodebuild test \
          -scheme Weather\ -\ Dev \
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'